### ISSUE TITLE
Crash when calling isLoginItemEnabled and loginitem is corrupt

### ISSUE THREAD

**Issue by dive-michiel** [nklizhe/NSBundle-LoginItem#4]
Thanks for the pod, great work!

Found an edge case bug today, reported by a beta tester of one of our apps.

It crashes on line 100 (CFRelease of appURL) if you have a "corrupt" item of the app as loginitem (see screenshot)

```
Crashed: com.apple.main-thread
EXC_BREAKPOINT EXC_I386_NMIFLT at 0x0000000000000000
NSBundle+LoginItem.m line 100
```

![screen-shot-2015-10-03-at-13 24](https://cloud.githubusercontent.com/assets/2650975/10262674/7bf8b332-69d2-11e5-827d-0db2f78e1a34.jpg)

Could it be a solution to use _bridge_transfer and let ARC do the memory management?

**Comment by nklizhe** [comment]
Thanks Michiel! Can you let me know what's the OS X version where it crashed?

**Comment by dive-michiel** [comment]
Hey Tom,

That would be 10.10.5, the corrupt login item had the same name as the app in question. 
Does the code check the app name, or the bundle identifier?

Problem is I don't know how to reproduce the corrupt login item (to test a solution).

![screen shot 2015-10-05 at 14 01 22](https://cloud.githubusercontent.com/assets/2650975/10279917/c1be2a94-6b69-11e5-8943-a93c37d9a4a5.png)

**Comment by nklizhe** [comment]
The code checks the app bundle path, not app name or bundle identifier.

**Comment by dive-michiel** [comment]
Pull request #5 is how we also solved the crash, though it doesn't set a login item anymore when you have a corrupt item (but at least it's not crashing).

How to get a corrupt login item (to reproduce):
- Add a program you can mis to login items with preferences window
- Delete that program and clear your trash bin
- Restart preferences -> corrupt login item

**Comment by nklizhe** [comment]
Thank you for the fix! @u-michiel
